# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-12-04 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171004_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='short_code',
            field=models.CharField(help_text='Convenient code/slug used to identify this Partner (e.g. for management commands.)', max_length=30, unique=True, verbose_name='Short Code'),
        ),
    ]
