# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2023-06-08 02:17
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0093_auto_20230104_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from='key'),
        ),
    ]
